version: '3.7'

services:

  php:
    build: .
    volumes:
      - ./src:/app
      - ./tests:/tests
    env_file:
      - .env
    networks:
      - network

  nginx:
    image: nginx:latest
    networks:
      - network
    ports:
      - "80:80"
    volumes:
      - ./src:/app
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7.20
    restart: always
    env_file:
      - .env
    networks:
      - network
    volumes:
      - mysqldata:/var/lib/mysql


networks:
  network:


volumes:
  mysqldata:

